spring.application.name=assignment1

#To use virtual threads to handle 200+ concurrent clients without exhausting the OS thread pool
spring.threads.virtual.enabled=true 

openai.api.key=${OPENAI_API_KEY:}
openai.api.url=https://api.openai.com/v1/audio/transcriptions
# spring.profiles.active=local

#Determining maximum file size
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

#Enable threads that are mid-execution to finish 
server.shutdown=graceful

spring.lifecycle.timeout-per-shutdown-phase=20s