spring.application.name=assignment1
spring.threads.virtual.enabled=true
openai.api.key=${OPENAI_API_KEY:}
openai.api.url=https://api.openai.com/v1/audio/transcriptions
# spring.profiles.active=local

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB